### ISSUE TITLE
Tesis / Práctica profesional

### ISSUE THREAD

**Issue by mrugna** [alumnosdcao/alumnosdcao.github.io#1]
En una de las reuniones se dijo que no iba a existir en los papeles la práctica profesional por alguna disposición de la UBA. En la resolución del consejo superior (que voy a adjuntar en un pull) habla de una "tesis de licenciatura" (comillas en el texto original) y, peor, subió de 160 a 320 horas la tesis.

Sugiero editar y borrar la parte de práctica profesional hasta tener más claro qué es lo que va a suceder y los plazos que el plan contempla.

**Comment by eliocamp** [comment]
Claro. En el texto la idea era dar a entender eso. Aunque no sabíamos lo de las 320 horas (no tenemos el texto último último).
